# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import players_pb2 as players__pb2


class PlayersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlayer = channel.unary_unary(
                '/players.Players/GetPlayer',
                request_serializer=players__pb2.PlayerRequest.SerializeToString,
                response_deserializer=players__pb2.Player.FromString,
                )


class PlayersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayer,
                    request_deserializer=players__pb2.PlayerRequest.FromString,
                    response_serializer=players__pb2.Player.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'players.Players', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Players(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/players.Players/GetPlayer',
            players__pb2.PlayerRequest.SerializeToString,
            players__pb2.Player.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
