# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: players.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplayers.proto\x12\x07players\"j\n\x06Player\x12\x12\n\nsummonerid\x18\x01 \x01(\t\x12\x14\n\x0csummonername\x18\x02 \x01(\t\x12\x0c\n\x04tier\x18\x03 \x01(\t\x12\x0c\n\x04wins\x18\x04 \x01(\x05\x12\x0e\n\x06losses\x18\x05 \x01(\x05\x12\n\n\x02lp\x18\x06 \x01(\x05\"#\n\rPlayerRequest\x12\x12\n\nsummonerid\x18\x01 \x01(\t2A\n\x07Players\x12\x36\n\tGetPlayer\x12\x16.players.PlayerRequest\x1a\x0f.players.Player\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'players_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYER']._serialized_start=26
  _globals['_PLAYER']._serialized_end=132
  _globals['_PLAYERREQUEST']._serialized_start=134
  _globals['_PLAYERREQUEST']._serialized_end=169
  _globals['_PLAYERS']._serialized_start=171
  _globals['_PLAYERS']._serialized_end=236
# @@protoc_insertion_point(module_scope)
